[paths]
data_dir = "/Volumes/Data/Pixarr/data"
db_path = "db/app.sqlite3"
review_subdir = "media/Review"
staging_subdir = "media/Staging"
thumb_subdir   = "thumb-cache"

[ingest]
allow_filename_dates = false
allow_file_dates = false     # if you ever want ModifyDate/FileModifyDate
dry_run_default = true

[quarantine]
missing_datetime = true
junk = true
unsupported_ext = true
zero_bytes = true
stat_error = true
move_failed = true
dupes = true

[staging.roots]
pc     = "pc"
icloud = "icloud"
sdcard = "sdcard"
other  = "other"

[ext]
# Used by /api/staging/list to decide which files to show
supported = ["jpg","jpeg","png","gif","webp","heic","heif","mp4","mov","webm","mkv","avi"]

# Used by /api/staging/stats to bucket files
image = ["jpg","jpeg","png","tif","tiff","gif","webp","heic","heif","avif"]
video = ["mp4","mov","m4v","avi","webm","mkv"]
raw   = ["dng","cr2","cr3","nef","arw","raf","rw2","orf","srw"]
